### ISSUE TITLE
How to predict？

### ISSUE THREAD

**Issue by Bella0818** [XixiLiu95/GEN#4]
Hello, is there a difference between Out-of-distribution (OOD) detection and Open set Recognition? For a dataset that includes a mixture of images from known classes and unknown classes, how does your model differentiate between each sample belonging to a known class or an unknown class during prediction?
Looking forward to your response！
@XixiLiu95

**Comment by XixiLiu95** [comment]
Hello Bella,

The difference between OOD detection and OSR is that OSR aims to not only classify ID samples correctly but also reject OOD samples. To achieve the latter goal, OOD scores such as GEN can be utilized to detect samples from unknown classes.  See more details in the paper ["Generalized Out-of-Distribution Detection: A Survey".](https://arxiv.org/pdf/2110.11334.pdf)

Best.
Xixi
